# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class:    App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path:  app_connexion
                check_path:  app_connexion
                default_target_path: app_profil
                username_parameter: email
                password_parameter: password

            logout:
                path: app_deconnexion
                target: app_accueil

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    access_control:
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
